#!/usr/bin/env bash
#compines if elif and else clauses
iter=1
while [ $iter -lt 11 ]
do
	if [ $iter -eq 4 ]
	then
		echo "bad luck"
	elif [ $iter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((iter++))
done
