#!/usr/bin/env bash
#demo the use of while loop together with if statement.
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((x++))
done
