#!/usr/bin/env bash
#demo the use of case clause
iter=1
while [ $iter -lt 21 ]
do
	echo $iter
	case $iter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((iter++))
done
