#!/usr/bin/env bash
#demo the idea of nested loops in bash programming.
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
